apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  ports:
  - port: 8083
    name: user-api
    targetPort: 8083
    protocol: TCP
  - port: 5556
    name: jmxexporter
    targetPort: 5556
    protocol: TCP
  selector:
    service: users-api
